# Generated by Django 2.0 on 2017-12-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribes',
            new_name='Subscriber',
        ),
    ]
